#!/usr/bin/env python3
"""Port one dataset from the MySQL corpus to PostgreSQL: write its files, then load them.

  python3 -m megasamples pg-port <dataset> [--files-only]

Reads the model from the MySQL build server (information_schema) and the data from the MySQL Shell
dump under build/mysql/dumps/<dataset>/, and writes build/postgres/<dataset>/:

    model.json         the engine-neutral model the DDL was generated from (the adapter reads it)
    schema.sql         CREATE TABLE with primary keys, defaults, generated columns, enum checks
    data/<table>.tsv   COPY text format, one file per table; data/tables.tsv lists them in load order
    indexes.sql        secondary indexes
    constraints.sql    foreign keys, checks, identity sequences advanced past the loaded keys
    dropped.txt        what PostgreSQL does not carry, one line each, with the reason

then loads them into the PostgreSQL build server: CREATE DATABASE, schema, \\copy per table,
indexes, constraints, ANALYZE. The image builder replays the same files (engines/postgres/Dockerfile).
Geometry columns are stored as WKB: the dump carries MySQL's internal form, a 4-byte SRID before
the WKB, and those four bytes are dropped so the stored value is what ST_AsBinary returns.
"""
import argparse, dataclasses, json, os, shutil, sys, time

from megasamples import datasets as inventory
from megasamples.engines.postgres import server as pg
from megasamples.engines.mysql import dump as dumper, server as mysql
from megasamples.paths import engine_build_dir, rel
from megasamples.port import ddl, model, record, tsv, typemap


def out_dir(dataset):
    return os.path.join(engine_build_dir("postgres"), dataset)


def setval_statements(database, dialect):
    """Advance every identity sequence past the largest key that was loaded."""
    out = []
    for t in database.tables:
        for c in t.columns:
            if c.auto_increment:
                out.append(f"SELECT setval(pg_get_serial_sequence('{dialect.quote(t.name)}', '{c.name}'), "
                           f"COALESCE(MAX({dialect.quote(c.name)}), 0) + 1, false) FROM {dialect.quote(t.name)};")
    return out


def write_files(dataset):
    cfg = inventory.load(dataset)
    schema = cfg["database"]
    dumps = os.path.join(engine_build_dir("mysql"), "dumps", dataset)
    mysql.start()
    if not os.path.exists(os.path.join(dumps, "@.json")):
        dumper.dump(dataset)
    database = model.extract(schema)
    if not database.tables:
        sys.exit(f"{dataset}: `{schema}` has no tables in the MySQL build server; run: make {dataset}")
    target = out_dir(dataset)
    shutil.rmtree(target, ignore_errors=True)
    os.makedirs(os.path.join(target, "data"))
    rendered = ddl.render(database, "postgres")
    dialect = ddl.DIALECTS["postgres"]

    with open(os.path.join(target, "model.json"), "w", encoding="utf-8") as fh:
        json.dump(dataclasses.asdict(database), fh, indent=1)
    with open(os.path.join(target, "schema.sql"), "w", encoding="utf-8") as fh:
        fh.write("-- generated by megasamples pg-port from the MySQL corpus; do not edit\n\n")
        fh.write("\n\n".join(rendered["schema"]) + "\n")
    with open(os.path.join(target, "indexes.sql"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(rendered["indexes"]) + "\n")
    with open(os.path.join(target, "constraints.sql"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(rendered["constraints"] + setval_statements(database, dialect)) + "\n")
    with open(os.path.join(target, "dropped.txt"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(rendered["dropped"]) + ("\n" if rendered["dropped"] else ""))
    record.write(dataset, "postgres", rendered)

    started = time.time()
    total = 0
    with open(os.path.join(target, "data", "tables.tsv"), "w", encoding="utf-8") as listing:
        for table in model.load_order(database):
            dump = tsv.TableDump(dumps, schema, table.name)
            # a stored generated column is not in the dump (it cannot be inserted); the engine
            # computes it from its own expression, and the digest check proves the values agree
            loaded = [c for c in table.columns if not c.generated]
            if dump.columns != [c.name for c in loaded]:
                sys.exit(f"{dataset}.{table.name}: dump column order {dump.columns} differs from the model's "
                         f"insertable columns {[c.name for c in loaded]}")
            geometry = {i for i, c in enumerate(loaded) if c.data_type in typemap.GEOMETRY_KINDS}
            n = tsv.write_postgres(dump, os.path.join(target, "data", f"{table.name}.tsv"), strip_srid=geometry)
            total += n
            cols = ",".join(dialect.quote(c.name) for c in loaded)
            listing.write(f"{table.name}\t{table.name}.tsv\t{cols}\n")
    print(f"  . {dataset}: {len(database.tables)} tables, {total:,} rows written to {rel(target)} "
          f"in {time.time() - started:.1f}s; {len(rendered['dropped'])} object(s) not ported (dropped.txt)")
    return database


def load(dataset):
    cfg = inventory.load(dataset)
    schema = cfg["database"]
    target = out_dir(dataset)
    inside = f"/build/postgres/{dataset}"
    pg.start()
    started = time.time()
    pg.psql(f'DROP DATABASE IF EXISTS "{schema}"')
    pg.psql(f'CREATE DATABASE "{schema}" TEMPLATE template0 ENCODING \'UTF8\'')
    pg.psql_file(f"{inside}/schema.sql", schema)
    n_tables = 0
    with open(os.path.join(target, "data", "tables.tsv"), encoding="utf-8") as listing:
        for line in listing:
            table, file, cols = line.rstrip("\n").split("\t")
            pg.psql(f'\\copy "{table}" ({cols}) FROM \'{inside}/data/{file}\' WITH (FORMAT text)', schema)
            n_tables += 1
    pg.psql_file(f"{inside}/indexes.sql", schema)
    pg.psql_file(f"{inside}/constraints.sql", schema)
    pg.psql("ANALYZE", schema)
    size = pg.rows(f"SELECT pg_size_pretty(pg_database_size('{schema}'))")[0][0]
    print(f"  . {dataset} loaded into PostgreSQL in {time.time() - started:.1f}s: {n_tables} tables, {size}")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("datasets", nargs="+")
    ap.add_argument("--files-only", action="store_true", help="write the port files without loading")
    a = ap.parse_args(argv)
    for d in a.datasets:
        write_files(d)
        if not a.files_only:
            load(d)
    return 0


if __name__ == "__main__":
    sys.exit(main())
