"""The port toolkit without Docker: type map, DDL emission, TSV escapes, canonical digests."""
from megasamples import canon
from megasamples.port import ddl, model, tsv, typemap


def col(name, data_type, column_type=None, nullable=True, default=None, extra="", **kw):
    fields = dict(name=name, data_type=data_type, column_type=column_type or data_type, nullable=nullable,
                  default=default, extra=extra, generation=None, char_len=None, precision=None, scale=None,
                  fsp=None, charset="utf8mb4", collation="utf8mb4_0900_ai_ci", ordinal=1)
    fields.update(kw)
    return model.Column(**fields)


def test_unsigned_integers_widen():
    assert typemap.postgres(col("a", "int", "int unsigned")) == "bigint"
    assert typemap.postgres(col("a", "int")) == "integer"
    assert typemap.postgres(col("a", "tinyint", "tinyint(1)")) == "smallint"      # never boolean
    assert typemap.postgres(col("a", "bigint", "bigint unsigned")) == "numeric(20,0)"
    assert typemap.sqlite(col("a", "int", "int unsigned")) == "INTEGER"


def test_decimal_and_time_precision_survive():
    assert typemap.postgres(col("p", "decimal", "decimal(19,4)", precision=19, scale=4)) == "numeric(19,4)"
    assert typemap.sqlite(col("p", "decimal", "decimal(19,4)", precision=19, scale=4)) == "DECIMAL(19,4)"
    assert typemap.postgres(col("t", "datetime", "datetime(6)", fsp=6)) == "timestamp(6) without time zone"
    assert typemap.postgres(col("t", "datetime")) == "timestamp(0) without time zone"


def test_enum_becomes_text_with_a_check_and_set_becomes_text():
    c = col("rating", "enum", "enum('G','PG','PG-13')", default="G")
    assert c.enum_values == ["G", "PG", "PG-13"]
    t = model.Table("s", "film", columns=[c], indexes=[])
    sql, dropped = ddl.schema(t, ddl.DIALECTS["postgres"])
    assert "\"rating\" text DEFAULT 'G' CHECK (\"rating\" IN ('G', 'PG', 'PG-13'))" in sql
    assert dropped == []
    assert typemap.postgres(col("f", "set", "set('a','b')")) == "text"


def test_sqlite_rowid_alias_for_a_single_integer_auto_increment_key():
    pk = model.Index("PRIMARY", True, "BTREE", [("id", None)], primary=True)
    t = model.Table("s", "t", columns=[col("id", "int", nullable=False, extra="auto_increment"),
                                       col("name", "varchar", "varchar(10)", char_len=10)], indexes=[pk])
    sql, _ = ddl.schema(t, ddl.DIALECTS["sqlite"])
    assert '"id" INTEGER PRIMARY KEY' in sql and "PRIMARY KEY (" not in sql
    sql, _ = ddl.schema(t, ddl.DIALECTS["postgres"])
    assert '"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL' in sql and 'PRIMARY KEY ("id")' in sql


def test_checks_are_translated_or_dropped_with_a_reason():
    t = model.Table("s", "t", columns=[col("c", "varchar", "varchar(5)", char_len=5)], indexes=[],
                    checks=[model.Check("ck_upper", "(upper(`c`) in (_utf8mb4\\'A\\',_utf8mb4\\'B\\'))"),
                            model.Check("ck_re", "regexp_like(`c`,_utf8mb4\\'^[A-Z]$\\')")])
    stmts, dropped = ddl.constraints(t, ddl.DIALECTS["postgres"])
    assert stmts[0].endswith("CHECK ((upper(\"c\") in ('A','B')));") and len(stmts) == 2
    # SQLite cannot add a constraint later, so they are declared inline by schema()
    assert ddl.constraints(t, ddl.DIALECTS["sqlite"]) == ([], [])
    sql, dropped = ddl.schema(t, ddl.DIALECTS["sqlite"])
    assert 'CONSTRAINT "ck_upper" CHECK ((upper("c") in (\'A\',\'B\')))' in sql
    assert "ck_re" not in sql and len(dropped) == 1 and "regexp_like" in dropped[0]


def test_fulltext_and_spatial_indexes_are_dropped_named():
    t = model.Table("s", "t", columns=[col("c", "text")], indexes=[
        model.Index("ft", False, "FULLTEXT", [("c", None)]), model.Index("ix", False, "BTREE", [("c", None)])])
    stmts, dropped = ddl.indexes(t, ddl.DIALECTS["postgres"])
    assert stmts == ['CREATE INDEX "t_ix" ON "t" ("c");'] and dropped == ["t.ft: FULLTEXT index: not ported"]


def test_tsv_escapes_round_trip_into_postgres_copy_format():
    assert tsv.unescape(b"\\N") is None
    assert tsv.unescape(b"a\\tb\\nc\\\\d") == b"a\tb\nc\\d"
    assert tsv.postgres_field("x\ty\r\n\\") == "x\\ty\\r\\n\\\\"
    assert tsv.postgres_field(b"\x00\x01") == "\\\\x0001"
    assert tsv.postgres_line(b"1\tplain\t\\N", ()) == b"1\tplain\t\\N"
    assert tsv.postgres_line(b"1\tAAEC", [1]) == b"1\t\\\\x000102"


def test_canonical_digest_is_the_same_definition_on_both_sides():
    # the SQL side hashes CONCAT_WS(CHAR(31), ...) with NULL as CHAR(0); the Python side must agree
    assert canon.row_digest(["1", None, "x"]) == int(__import__("hashlib").sha256("1\x1f\x00\x1fx".encode()).hexdigest()[:16], 16)
    f = canon.fold([5, 9])
    assert f == {"n": 2, "x": 5 ^ 9, "s": 14}


def test_index_names_stay_within_postgresql_limit_and_map_back():
    long_index = "ix_address_addressline1_addressline2_city_stateprovince_4eb9021d"
    physical = ddl.physical_index_name("address", long_index)
    assert len(physical.encode()) <= 63 and physical.startswith("address_ix_address")
    assert ddl.physical_index_name("film", "idx_title") == "film_idx_title"
    assert ddl.physical_index_name("address", long_index) == physical     # deterministic


def test_constraint_and_index_names_are_shortened_the_same_way():
    long_name = "fk_productmodelproductdescriptionculture_productdescrip_f5ffc2f4"
    assert len(ddl.short_name(long_name).encode()) <= 63
    assert ddl.short_name("fk_short") == "fk_short"


def test_identity_columns_keep_an_integer_type_postgresql_accepts():
    c = col("page_id", "bigint", "bigint unsigned", nullable=False, extra="auto_increment")
    assert typemap.postgres(c) == "bigint"
    assert typemap.postgres(col("n", "bigint", "bigint unsigned")) == "numeric(20,0)"


def test_sqlite_canonical_rendering_matches_mysql_text_forms():
    from megasamples.engines.sqlite.adapter import canonical
    assert canonical(4.99, "decimal", 2) == "4.99"
    assert canonical(0.5, "decimal", 2) == "0.50"
    assert canonical(3, "decimal", 4) == "3.0000"
    assert canonical("2006-02-15 05:03:42", "datetime", None) == "2006-02-15 05:03:42.000000"
    assert canonical("2006-02-15 05:03:42.12", "datetime", None) == "2006-02-15 05:03:42.120000"
    assert canonical("ab  ", "char", None) == "ab"
    assert canonical(b"\x01\xff", "varbinary", None) == "01ff"
    assert canonical(7, "tinyint", None) == "7"
    assert canonical(None, "int", None) is None
