#!/usr/bin/env python3
"""Port one dataset from the MySQL corpus to a SQLite file.

  python3 -m megasamples sqlite-port <dataset>

Reads the model from the MySQL build server and the data from the MySQL Shell dump, and writes
build/sqlite/<dataset>/:

    <database>.sqlite  the database: tables with primary keys, foreign keys and checks declared
                       inline (SQLite cannot add them later), data, then secondary indexes; VACUUMed;
                       rollback journal, so the file is portable as shipped
    schema.sql         the DDL it was created from, for review
    model.json         the engine-neutral model (the adapter reads it)
    dropped.txt        what SQLite does not carry, one line each, with the reason

Values are inserted as the dump's text; SQLite's type affinity converts integers and decimals into
numbers, and the declared types (`DECIMAL(10,2)`, `DATETIME`, ...) are kept for readers that use them.
Geometry is stored as WKB (the dump's 4-byte SRID prefix removed). Foreign-key enforcement is a
per-connection pragma in SQLite; the file is loaded with it off and verified afterwards.
"""
import argparse, dataclasses, json, os, shutil, sqlite3, sys, time

from megasamples import datasets as inventory, registry
from megasamples.engines.mysql import dump as dumper, server as mysql
from megasamples.paths import engine_build_dir, rel
from megasamples.port import ddl, model, record, tsv, typemap, views as view_port


def out_dir(dataset):
    return os.path.join(engine_build_dir("sqlite"), dataset)


def rows_for(loaded, dump):
    geometry = {i for i, c in enumerate(loaded) if c.data_type in typemap.GEOMETRY_KINDS}
    for row in dump.rows():
        for i in geometry:
            if isinstance(row[i], bytes):
                row[i] = row[i][4:]
        yield row


def write(dataset):
    cfg = inventory.load(dataset)
    schema = cfg["database"]
    dumps = os.path.join(engine_build_dir("mysql"), "dumps", dataset)
    mysql.start()
    if not os.path.exists(os.path.join(dumps, "@.json")):
        dumper.dump(dataset)
    database = model.extract(schema)
    if not database.tables:
        sys.exit(f"{dataset}: `{schema}` has no tables in the MySQL build server; run: make {dataset}")
    target = out_dir(dataset)
    shutil.rmtree(target, ignore_errors=True)
    os.makedirs(target)
    rendered = ddl.render(database, "sqlite")
    view_sql = rendered["views"]
    ported_views = [st.split('"')[1] for st in view_sql]
    with open(os.path.join(target, "model.json"), "w", encoding="utf-8") as fh:
        doc = dataclasses.asdict(database)
        doc["ported_views"] = ported_views
        doc["ported_triggers"] = [s.split('"')[1] for s in rendered["triggers"] if s.startswith("CREATE TRIGGER")]
        json.dump(doc, fh, indent=1)
    with open(os.path.join(target, "schema.sql"), "w", encoding="utf-8") as fh:
        fh.write("-- generated by megasamples sqlite-port from the MySQL corpus; do not edit\n\n")
        fh.write("\n\n".join(rendered["schema"]) + "\n\n" + "\n".join(rendered["indexes"]) + "\n")
    with open(os.path.join(target, "dropped.txt"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(rendered["dropped"]) + ("\n" if rendered["dropped"] else ""))
    record.write(dataset, "sqlite", rendered)

    path = os.path.join(target, f"{schema}.sqlite")
    started = time.time()
    con = sqlite3.connect(path)
    con.execute("PRAGMA journal_mode=OFF")
    con.execute("PRAGMA synchronous=OFF")
    con.execute("PRAGMA foreign_keys=OFF")
    con.execute("PRAGMA application_id=0x4D534D50")        # 'MSMP': this file came from megasamples
    con.executescript("\n".join(rendered["schema"]))
    total = 0
    for table in model.load_order(database):
        dump = tsv.TableDump(dumps, schema, table.name)
        # a stored generated column is not in the dump; SQLite computes it from its own expression
        loaded = [c for c in table.columns if not c.generated]
        if dump.columns != [c.name for c in loaded]:
            sys.exit(f"{dataset}.{table.name}: dump column order {dump.columns} differs from the model's "
                     f"insertable columns {[c.name for c in loaded]}")
        placeholders = ", ".join("?" for _ in loaded)
        cols = ", ".join(ddl.DIALECTS["sqlite"].quote(c.name) for c in loaded)
        cur = con.executemany(f'INSERT INTO "{table.name}" ({cols}) VALUES ({placeholders})', rows_for(loaded, dump))
        total += cur.rowcount
    con.executescript("\n".join(rendered["indexes"]))
    if view_sql:
        con.executescript("\n".join(view_sql))
    if rendered["triggers"]:
        con.executescript("\n".join(rendered["triggers"]))
    con.commit()
    con.execute("PRAGMA journal_mode=DELETE")
    con.execute("VACUUM")
    con.close()
    size = os.path.getsize(path) / 1048576
    print(f"  . {dataset}: {len(database.tables)} tables, {total:,} rows -> {rel(path)} ({size:.1f} MB) "
          f"in {time.time() - started:.1f}s; {len(rendered['dropped'])} object(s) not ported (dropped.txt)")
    return database


def write_registry(path, datasets):
    """megasamples.sqlite: the provenance registry, the same rows the other engines carry."""
    if os.path.exists(path):
        os.remove(path)
    con = sqlite3.connect(path)
    con.executescript("""
        CREATE TABLE datasets (
          name TEXT NOT NULL PRIMARY KEY, tier TEXT NOT NULL, record TEXT NOT NULL,
          upstream_version TEXT, licenses TEXT, artifacts TEXT, row_counts TEXT, build_id TEXT,
          engine TEXT NOT NULL DEFAULT 'sqlite', not_ported TEXT
        );
        """)
    sql = registry.render(datasets, os.environ.get("MEGASAMPLES_BUILD_ID", "dev"), "sqlite", "sqlite")
    con.executescript(sql.replace("-- Generated", "-- Generated"))
    con.commit()
    con.execute("VACUUM")
    con.close()


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("datasets", nargs="+")
    a = ap.parse_args(argv)
    for d in a.datasets:
        write(d)
    return 0


if __name__ == "__main__":
    sys.exit(main())
