"""Generate compose.yaml from megasamples.yaml: the stack is exactly what the configuration names.

    python3 -m megasamples compose [--check]

One Compose project, `sql-megasamples`, that comes up and goes down together: the engines chosen,
the consoles chosen, and the landing page. Rules the generated file follows, and why:

* Every service carries a `mem_limit`. A container with no limit can see the whole VM, so one
  process going wide takes the machine down rather than failing on its own.
* Every port binds to 127.0.0.1. An unauthenticated database UI should not appear on the network
  because someone opened a laptop in a cafe; publishing it more widely is a deliberate edit.
* Images are pinned by digest. On a machine whose Docker daemon cannot reach the registry over its
  own network stack, `megasamples pull-image` fetches them over IPv4 and the digest is what makes
  the two paths name the same bytes.
* The consoles are started only when an engine they can browse is in the stack, and each console
  is configured for every engine present, read-only account first.
* Nothing here is baked into any image: `docker compose up -d mysql` is the same database with no UI.

Passwords come from .env (see .env.example); compose passes each value to the server, which applies
it at startup, and to every console, so the two cannot drift apart.
"""
import argparse, os, sys

import yaml

from megasamples import config as stack, consoles as console_registry, engines as engine_registry
from megasamples.paths import COMPOSE, rel

PROJECT = "sql-megasamples"
HEADER = ("# Generated by `python3 -m megasamples compose` from megasamples.yaml. Do not edit: the next\n"
          "# `make up` rewrites it. ARCHITECTURE.md section 6 explains every rule the file follows.\n")


def console_service(console, cfg, engines):
    port = cfg.ports.get(console.name)
    service = {
        "image": console.image,
        "mem_limit": console.mem_limit,
        "container_name": console.container,
        "ports": [f"127.0.0.1:{port}:{console.container_port}"],
        "restart": "unless-stopped",
    }
    if console.volumes:
        service["volumes"] = list(console.volumes)
    present = [e for e in engines if not console.engines or e.name in console.engines]
    if present:
        service["depends_on"] = {e.name: {"condition": "service_healthy"} for e in present}
    env = {}
    for e in present:
        env.update(e.console_environment(console.name, cfg))
    if console.name == "landing":
        env = {}
    if env:
        service["environment"] = env
    return service


def render(cfg):
    engines = [engine_registry.get(n) for n in cfg.engines]
    services = {}
    for e in engines:
        services[e.name] = e.compose_service(cfg)
    for name in cfg.consoles:
        c = console_registry.get(name)
        if c.engines and not any(e.name in c.engines for e in engines):
            continue
        services[c.name] = console_service(c, cfg, engines)
    doc = {"name": PROJECT, "services": services}
    return HEADER + yaml.safe_dump(doc, sort_keys=False, default_flow_style=False, width=100)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if compose.yaml would change")
    ap.add_argument("--out", default=COMPOSE)
    a = ap.parse_args(argv)
    cfg = stack.load()
    problems = cfg.validate()
    if problems:
        for p in problems:
            print(f"  x {p}")
        return 2
    text = render(cfg)
    current = open(a.out, encoding="utf-8").read() if os.path.exists(a.out) else None
    if a.check:
        if current == text:
            print(f"  . {rel(a.out)} matches {cfg.source}")
            return 0
        print(f"  x {rel(a.out)} is stale; run `make compose`")
        return 1
    if current != text:
        with open(a.out, "w", encoding="utf-8") as fh:
            fh.write(text)
    print(f"  . {rel(a.out)}: {', '.join(cfg.engines)} + {', '.join(cfg.consoles)} (from {cfg.source})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
