"""Prove the ports are reproducible: re-render every port's DDL and compare it with what is committed.

  python3 -m megasamples ports-check [dataset ...] [--write]

`--write` regenerates the records instead of comparing them (the same code path a port runs). The files under datasets/<name>/ports/ are the output of one deterministic program -- the model read
from information_schema, one type-mapping table, one DDL emitter -- and nothing else. This check
regenerates them for every dataset that is loaded in the MySQL build server and fails if a byte
differs, which is how a change to the mapping shows up as a diff and how a hand edit is caught. A
dataset that is not loaded is reported as not checked rather than passed.
"""
import argparse, os, sys

import yaml

from megasamples import datasets as inventory
from megasamples.engines.mysql import server as db
from megasamples.paths import DATASETS
from megasamples.port import ddl, model, record


def rendered_files(dataset):
    """{filename: content} as record.write would produce them now, for both dialects."""
    database = model.extract(inventory.load(dataset)["database"])
    out, dropped = {}, {}
    result_columns = record.read_result_sets(dataset)
    for engine in ("postgres", "sqlite"):
        r = ddl.render(database, engine, result_columns)
        dropped[engine] = list(r["dropped"])
        header = (f"-- {engine} DDL for `{dataset}`, generated by megasamples from the MySQL corpus. Do not edit:\n"
                  f"-- the next port rewrites it. Data is loaded from the MySQL Shell dump, not from here.\n\n")
        body = "\n\n".join(r["schema"]) + "\n"
        if r["indexes"]:
            body += "\n" + "\n".join(r["indexes"]) + "\n"
        if r["constraints"]:
            body += "\n" + "\n".join(r["constraints"]) + "\n"
        if r.get("routines"):
            body += "\n" + "\n\n".join(r["routines"]) + "\n"
        if r.get("views"):
            body += "\n" + "\n\n".join(r["views"]) + "\n"
        if r.get("triggers"):
            body += "\n" + "\n\n".join(r["triggers"]) + "\n"
        out[f"{engine}.sql"] = header + body
        if engine == "postgres":
            out["notes.yaml"] = record.notes_text(r["notes"])
            if result_columns:
                out["result_sets.yaml"] = record.result_sets_text(result_columns)
    out["not_ported.yaml"] = record.not_ported_text(dropped)
    return out


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("datasets", nargs="*")
    ap.add_argument("--write", action="store_true", help="regenerate the records instead of comparing")
    a = ap.parse_args(argv)
    names = a.datasets or ([d for d in inventory.names() if os.path.exists(os.path.join(DATASETS, d, "ports", "not_ported.yaml"))]
                           if not a.write else inventory.core())
    if not names:
        print("  . no port records under datasets/*/ports/ yet; nothing to check")
        return 0
    if db.container_state() != "running":
        print(f"  ? {len(names)} port record(s) not checked: the MySQL build server is not running")
        return 0
    loaded = {r[0] for r in db.rows("SELECT schema_name FROM information_schema.schemata")}
    checked, skipped, stale = 0, [], []
    for name in names:
        database = inventory.load(name)["database"]
        if database not in loaded:
            skipped.append(name)
            continue
        for filename, content in rendered_files(name).items():
            path = os.path.join(DATASETS, name, "ports", filename)
            if a.write:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                with open(path, "w", encoding="utf-8") as fh:
                    fh.write(content)
                continue
            current = open(path, encoding="utf-8").read() if os.path.exists(path) else None
            if current != content:
                stale.append(f"datasets/{name}/ports/{filename}")
        checked += 1
    if a.write:
        print(f"  . port records written for {checked} dataset(s)" + (f"; {len(skipped)} not loaded, skipped" if skipped else ""))
        return 0
    for s in stale:
        print(f"  x {s} differs from what the port generates now")
    print(f"  . ports reproducible for {checked} dataset(s)" + (f"; {len(skipped)} not loaded in the build server, not checked" if skipped else ""))
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
