#!/usr/bin/env python3
"""Generate CATALOGUE.md: every database in the project, what it is, and what its licence requires.

  python3 scripts/catalogue.py [--container megasamples-mysql] [--check]

The README says what the project is; this says what is *in* it. One row per dataset, with the tier
that decides whether it is in the image, its measured shape, its licence, and whether that licence
asks anything of someone who redistributes it.

Sources, in order of authority: `megasamples.datasets` inside the running image for the measured
shape (the same table `tests/image_test.py` asserts against), `datasets/*/dataset.yaml` for the tier
and licence ids of everything else, and the knowledge records for the one-line description. Nothing
here is typed by hand, so it cannot drift from what was built. `--check` exits non-zero if the file
would change, which is what `make check` runs.
"""
import argparse, os, subprocess, sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "CATALOGUE.md")
GENERATED = ("<!-- Generated by scripts/catalogue.py from megasamples.datasets and datasets/*/dataset.yaml.\n"
             "     Do not edit by hand: `make catalogue` overwrites it. -->\n")
TIER_NOTE = {
    "core": "in the image",
    "core-medium": "in the image",
    "extended": "opt-in; `make <name>`",
    "generated": "generated on your machine",
    "user-fetched": "you download it; never redistributed",
    # citibike and divvy sit here because *this project* ships none of their data; the loaders are
    # shipped and you run them yourself, which is where their licences put the boundary
    "not-shipped": "loaders only; you fetch the data, it is never redistributed",
}


def query(container, sql):
    p = subprocess.run(["docker", "exec", container, "mysql", "-uroot", "-proot", "-N", "--batch",
                        "-e", sql], capture_output=True, text=True)
    return [l.split("\t") for l in p.stdout.splitlines() if l.strip()] if p.returncode == 0 else []


def record_description(path):
    if not path or not os.path.exists(os.path.join(ROOT, path)):
        return ""
    text = open(os.path.join(ROOT, path), encoding="utf-8").read()
    try:
        meta = yaml.safe_load(text.split("---", 2)[1])
    except Exception:
        return ""
    return (meta or {}).get("description", "").split(";")[0].strip()


# The curated tags on each licence record, mapped to what they mean for someone redistributing.
# Read from the record's frontmatter rather than inferred from its prose: scanning the text for
# "share-alike" labels MIT as copyleft, because the MIT record explains that it is *not* one.
TAG_MEANS = {
    "share-alike": "share-alike",
    "copyleft": "share-alike",
    "attribution": "attribution",
    "attribution-required": "attribution, verbatim disclaimer",
    "permissive": "ship the notice",
    "public-domain": "none",
    "redistribution-blocked": "**cannot be redistributed**",
    "proprietary": "**build-time only, never redistributed**",
    "eula": "**build-time only, never redistributed**",
}


def licence_obligations():
    """What each licence asks of a redistributor, from the curated tags on its record."""
    out = {}
    d = os.path.join(ROOT, "knowledge", "licenses")
    for f in sorted(os.listdir(d)):
        if not f.endswith(".md") or f == "index.md":
            continue
        text = open(os.path.join(d, f), encoding="utf-8").read()
        try:
            meta = yaml.safe_load(text.split("---", 2)[1]) or {}
        except Exception:
            meta = {}
        asks = [TAG_MEANS[t] for t in (meta.get("tags") or []) if t in TAG_MEANS]
        spread = [part for a in asks for part in a.split(", ")]
        out[f[:-3]] = ", ".join(dict.fromkeys(spread)) or "see the record"
    return out


def collect(container):
    # Only the registry is used for the measured shape. `information_schema` sizes are not: InnoDB
    # reports a slightly different data_length after a restart, which would make this file differ
    # from itself on every run and `make check` fail for no reason. Table and row counts are baked
    # at build time and do not move.
    measured = {r[0]: r for r in query(container, "SELECT name, tier, JSON_LENGTH(row_counts), "
                                                 "JSON_EXTRACT(licenses, '$[0]') FROM megasamples.datasets")}
    rows_by_db = {r[0]: r[1] for r in query(container,
             "SELECT name, (SELECT SUM(v) FROM JSON_TABLE(row_counts, '$.*' COLUMNS (v BIGINT PATH '$')) t) "
             "FROM megasamples.datasets")}

    out = []
    for d in sorted(os.listdir(os.path.join(ROOT, "datasets"))):
        spec_path = os.path.join(ROOT, "datasets", d, "dataset.yaml")
        if not os.path.exists(spec_path):
            continue
        spec = yaml.safe_load(open(spec_path, encoding="utf-8")) or {}
        db = spec.get("database", d)
        append = bool(spec.get("append"))
        m = measured.get(d)
        out.append(dict(
            name=d,
            database=db,
            tier=spec.get("tier", "?"),
            licences=spec.get("licenses", []) or [],
            record=spec.get("record", ""),
            append=append,
            tables=int(m[2]) if m else None,
            rows=int(rows_by_db[d]) if m and rows_by_db.get(d, "").isdigit() else None,
        ))
    return out


def render(items):
    asks = licence_obligations()
    in_image = [i for i in items if i["tables"] is not None]
    total_tables = sum(i["tables"] for i in in_image)
    total_rows = sum(i["rows"] or 0 for i in in_image)

    L = [GENERATED.rstrip(), "", "# Catalogue", "",
         f"**{len(in_image)} databases in the image** — {total_tables:,} tables, {total_rows:,} rows — "
         "plus the datasets that are opt-in, generated on your machine, or that you fetch yourself.",
         "", "Generated from the registry inside the built image and from `datasets/*/dataset.yaml`, so",
         "it cannot drift from what was actually built. `README.md` explains the project;",
         "`datasets/<name>/PROVENANCE.md` has the full derivation of any one row.", ""]

    for tier in ("core", "core-medium", "extended", "generated", "user-fetched", "not-shipped"):
        group = [i for i in items if i["tier"] == tier]
        if not group:
            continue
        L += [f"## {tier} — {TIER_NOTE.get(tier, '')}", "",
              "| database | tables | rows | licence | asks of a redistributor |",
              "|---|---:|---:|---|---|"]
        for i in group:
            lic = ", ".join(f"[{x}](knowledge/licenses/{x}.md)" for x in i["licences"]) or "—"
            parts = [p for x in i["licences"] for p in asks.get(x, "").split(", ") if p]
            parts = list(dict.fromkeys(parts))
            if len(parts) > 1:                      # "none" alongside a real obligation is noise
                parts = [p for p in parts if p != "none"]
            ask = ", ".join(parts) or "—"
            t = f"{i['tables']:,}" if i["tables"] is not None else "—"
            r = f"{i['rows']:,}" if i["rows"] else "—"
            label = f"`{i['name']}`" + (f"<br>appends to `{i['database']}`" if i["append"] else "")
            L.append(f"| {label} | {t} | {r} | {lic} | {ask} |")
        L.append("")

    L += ["TPC-C is generated too, by `make load-tpcc`, but has no `datasets/*/dataset.yaml` and so no",
          "row above: it is loaded by `scripts/tpcc_load.py` through sysbench rather than by the",
          "fetch/stage/load pipeline, and it is the one dataset with no pinned content digests, because",
          "its generator does not produce the same rows twice (`knowledge/datasets/tpc-c.md`).",
          "",
          "## What the obligations mean", "",
          "* **attribution** — the notice in `datasets/<name>/LICENSE` and the root `NOTICE.md` has to",
          "  travel with the data, including inside a derived image.",
          "* **share-alike** — a modified or extended version of that database must be offered under",
          "  the same licence. This applies to `employees`, `lahman`, the Stack Exchange datasets and",
          "  `wikipedia_simple`.",
          "* **verbatim disclaimer** — Chicago's terms require their disclaimer word for word, and",
          "  reserve the City's right to require distribution to stop. It is in `README.md` and",
          "  `NOTICE.md`.",
          "",
          "Citi Bike and Divvy are in this catalogue because the project ships loaders for them. Their",
          "data is never redistributed here in any form: both licences prohibit hosting or distributing",
          "it as a stand-alone dataset.", ""]
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--container", default="megasamples-mysql")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    items = collect(a.container)
    text = render(items)
    if a.check:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != text:
            print("  x CATALOGUE.md is out of date; run `make catalogue`")
            return 1
        print("  . CATALOGUE.md is up to date")
        return 0
    open(OUT, "w", encoding="utf-8").write(text)
    measured = sum(1 for i in items if i["tables"] is not None)
    print(f"  . wrote CATALOGUE.md: {len(items)} datasets, {measured} measured from the image")
    return 0


if __name__ == "__main__":
    sys.exit(main())
