#!/usr/bin/env python3
"""DDL fix-ups shared by the T-SQL and PL/SQL translators.

Both source dialects declare an identity column and then add its primary key in a separate
statement, which MySQL does not allow, so the fix belongs in one place rather than in each
translator.
"""
import re


# the column may be bare (Oracle) or backticked (T-SQL, after identifier mapping), and other
# attributes such as NOT NULL may sit between the type and AUTO_INCREMENT
IDENTITY_COL = re.compile(r"(?im)^\s*,?\s*`?(\w+)`?\s+[^,\n]*?\bAUTO_INCREMENT\b")


def inline_identity_pk(create_table, declared_pk=None):
    """Give an identity column a key inline, and report which later key that makes redundant.

    MySQL requires an AUTO_INCREMENT column to be a key the moment it is declared, but these schemas
    add the primary key afterwards with ALTER TABLE. Deferring the AUTO_INCREMENT instead does not
    work either: the rows are inserted with NULL in that column (Oracle's `GENERATED BY DEFAULT ON
    NULL` generates the value), so the later ALTER fails on NULLs.

    Which key to add depends on the primary key the script declares later, passed in as
    `declared_pk` (table -> column list):

    * the identity column alone -> declare it PRIMARY KEY here and drop the later ALTER as a
      duplicate, which is what the caller does with the returned pair;
    * a composite key such as AdventureWorks LT's SalesOrderDetail (SalesOrderID,
      SalesOrderDetailID) -> a plain KEY, because InnoDB only needs the AUTO_INCREMENT column to
      lead *some* index, and the real primary key still arrives with the ALTER;
    * nothing declared -> PRIMARY KEY, as before.
    """
    table = re.search(r"(?i)CREATE\s+TABLE\s+`?(\w+)`?", create_table)
    if not table or "AUTO_INCREMENT" not in create_table.upper():
        return create_table, None
    col = IDENTITY_COL.search(create_table)
    if not col:
        return create_table, None
    name, column = table.group(1).lower(), col.group(1).lower()
    if re.search(r"(?i)PRIMARY\s+KEY", create_table):
        return create_table, (name, column)                          # already keyed
    pk = (declared_pk or {}).get(name)
    key = "PRIMARY KEY" if pk is None or pk == [column] else "KEY"
    close = create_table.rfind(")")
    head = create_table[:close].rstrip().rstrip(",")
    return (head + f",\n  {key} (`{col.group(1)}`)\n" + create_table[close:],
            (name, column) if key == "PRIMARY KEY" else None)
