#!/usr/bin/env python3
"""DDL fix-ups shared by the T-SQL and PL/SQL translators.

Both source dialects declare an identity column and then add its primary key in a separate
statement, which MySQL does not allow, so the fix belongs in one place rather than in each
translator.
"""
import re


def without_literals(sql):
    """The statement with the contents of string literals blanked out.

    Keyword searches over DDL have to ignore literals: Oracle's own column comments say things like
    "primary key column", and once those are attached as MySQL COMMENT text a plain search for
    PRIMARY KEY finds one in a table that has none.
    """
    out, i, n = [], 0, len(sql)
    while i < n:
        if sql[i] != "'":
            out.append(sql[i]); i += 1; continue
        j = i + 1
        while j < n:
            if sql[j] == "'":
                if j + 1 < n and sql[j + 1] == "'":
                    j += 2; continue
                break
            j += 1
        out.append("'" + " " * (j - i - 1) + "'")
        i = j + 1
    return "".join(out)


# the column may be bare (Oracle) or backticked (T-SQL, after identifier mapping), and other
# attributes such as NOT NULL may sit between the type and AUTO_INCREMENT
IDENTITY_COL = re.compile(r"(?im)^\s*,?\s*`?(\w+)`?\s+[^,\n]*?\bAUTO_INCREMENT\b")


def inline_identity_pk(create_table, declared_pk=None):
    """Give an identity column a key inline, and report which later key that makes redundant.

    MySQL requires an AUTO_INCREMENT column to be a key the moment it is declared, but these schemas
    add the primary key afterwards with ALTER TABLE. Deferring the AUTO_INCREMENT instead does not
    work either: the rows are inserted with NULL in that column (Oracle's `GENERATED BY DEFAULT ON
    NULL` generates the value), so the later ALTER fails on NULLs.

    Which key to add depends on the primary key the script declares later, passed in as
    `declared_pk` (table -> column list):

    * the identity column alone -> declare it PRIMARY KEY here and drop the later ALTER as a
      duplicate, which is what the caller does with the returned pair;
    * a composite key such as AdventureWorks LT's SalesOrderDetail (SalesOrderID,
      SalesOrderDetailID) -> a plain KEY, because InnoDB only needs the AUTO_INCREMENT column to
      lead *some* index, and the real primary key still arrives with the ALTER;
    * nothing declared -> PRIMARY KEY, as before.
    """
    bare = without_literals(create_table)
    table = re.search(r"(?i)CREATE\s+TABLE\s+`?(\w+)`?", bare)
    if not table or "AUTO_INCREMENT" not in bare.upper():
        return create_table, None
    col = IDENTITY_COL.search(bare)
    if not col:
        return create_table, None
    name, column = table.group(1).lower(), col.group(1).lower()
    if re.search(r"(?i)PRIMARY\s+KEY", bare):
        return create_table, (name, column)                          # already keyed
    pk = (declared_pk or {}).get(name)
    key = "PRIMARY KEY" if pk is None or pk == [column] else "KEY"
    close = bare.rfind(")")
    head = create_table[:close].rstrip().rstrip(",")
    return (head + f",\n  {key} (`{col.group(1)}`)\n" + create_table[close:],
            (name, column) if key == "PRIMARY KEY" else None)


COLUMN_NAME = re.compile(r"^`(\w+)`")
NOT_A_COLUMN = re.compile(r"(?i)^\s*(PRIMARY\s+KEY|FOREIGN\s+KEY|CONSTRAINT|UNIQUE|KEY|INDEX|CHECK)\b")


def columns_of(create_table):
    """Column names of a translated CREATE TABLE, in declaration order.

    Comments are removed first: AdventureWorks documents its columns inline, and a comment such as
    "-- A customer may either be a person, a store, or a person who works for a store" carries commas
    that would otherwise split the column list and lose the columns after it.
    """
    body = create_table[create_table.index("(") + 1:create_table.rindex(")")]
    body = re.sub(r"--[^\n]*", "", body)
    body = re.sub(r"(?s)/\*.*?\*/", "", body)
    names, depth, item = [], 0, []
    for ch in body + ",":
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            text = "".join(item).strip()
            m = COLUMN_NAME.match(text)
            if m and not NOT_A_COLUMN.match(text):
                names.append(m.group(1))
            item = []
        else:
            item.append(ch)
    return names
