#!/usr/bin/env python3
"""Generate the licence and provenance files from the knowledge bundle (PLAN.md section 8.2).

  python3 scripts/gen_provenance.py [--no-measurements] [--check]

Writes `datasets/<name>/LICENSE` and `PROVENANCE.md` for every dataset, and the root `LICENSES.md`
and `NOTICE.md`. Everything comes from files already under version control -- `dataset.yaml`, the
dataset's knowledge record, the licence records, `manifest.yaml` and `name_map.yaml` -- so the
knowledge bundle stays the single source of truth and these files can never quietly disagree with it.

`--no-measurements` omits the section that depends on a build (measured row counts, pinned baselines),
which is what CI uses: `build/` is git-ignored and CI builds only a subset, so only the
knowledge-derived part can be compared there. `--check` writes nothing and exits non-zero if any file
would change, which is the same test phrased for a pre-commit hook.
"""
import argparse, hashlib, os, re, sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GENERATED = ("<!-- Generated by scripts/gen_provenance.py from knowledge/ and manifest.yaml.\n"
             "     Do not edit by hand: `make provenance` overwrites it. -->\n")


def read_record(path):
    """(frontmatter, {heading: body}) of an OKF record."""
    text = open(path, encoding="utf-8").read()
    _, front, body = text.split("---", 2)
    meta = yaml.safe_load(front)
    sections, current = {}, None
    for line in body.split("\n"):
        heading = re.match(r"^#\s+(.+?)\s*$", line)
        if heading:
            current = heading.group(1)
            sections[current] = []
        elif current:
            sections[current].append(line)
    return meta, {k: "\n".join(v).strip() for k, v in sections.items()}


def datasets():
    for path in sorted(os.listdir(os.path.join(ROOT, "datasets"))):
        config = os.path.join(ROOT, "datasets", path, "dataset.yaml")
        if os.path.exists(config):
            yield path, yaml.safe_load(open(config, encoding="utf-8"))


def artifacts_by_dataset():
    """Artifacts per dataset, resolved through `dataset.yaml` first.

    Grouping only by the artifact's own `dataset` field loses the datasets that are built from
    someone else's download: `enron_full` reads the same CMU tarball as `enron`, declares it in its
    `artifacts:` list, and would otherwise get an empty "Source artifacts" table -- a provenance file
    claiming to pin every byte while pinning none.
    """
    manifest = yaml.safe_load(open(os.path.join(ROOT, "manifest.yaml"), encoding="utf-8"))
    by_id = {art["id"]: art for art in manifest["artifacts"]}
    out = {}
    for art in manifest["artifacts"]:
        out.setdefault(art["dataset"], []).append(art)
    for name, cfg in datasets():
        # union, not replacement: `dvdstore` owns 52 artifacts in the manifest and names only 3 in
        # its dataset.yaml, so preferring the declared list would drop 49 pinned digests
        owned = out.get(name, [])
        have = {a["id"] for a in owned}
        extra = [by_id[i] for i in (cfg.get("artifacts") or []) if i in by_id and i not in have]
        if extra:
            out[name] = owned + extra
    return out


def licence_text(licence_id, records):
    meta, sections = records[licence_id]
    return meta, sections


def build_license_file(name, cfg, licences):
    lines = [f"Licence terms for the `{name}` database as redistributed by mysql-megasamples.", ""]
    lines.append("The data is not this project's work. Each licence below is the upstream one, and")
    lines.append("this database is offered under the same terms.")
    for licence_id in cfg.get("licenses", []):
        meta, sections = licences[licence_id]
        lines += ["", "=" * 78, "", meta["title"], "-" * len(meta["title"]), ""]
        if "Where the text lives" in sections:
            lines += [sections["Where the text lives"], ""]
        if "Attribution" in sections:
            lines += ["Attribution required:", "", sections["Attribution"], ""]
        if "Obligations" in sections:
            lines += ["Obligations:", "", sections["Obligations"]]
    return "\n".join(lines).rstrip() + "\n"


def section_starting(sections, prefix):
    """Records date their own headings ("# Accepted (2026-09-03, task X-02)"), so match the prefix."""
    for heading, body in sections.items():
        if heading.startswith(prefix):
            return body
    return ""


def build_provenance(name, cfg, arts, record, measurements, licences):
    meta, sections = record
    out = [GENERATED, f"# Provenance — `{name}`", "",
           f"**Upstream:** {meta.get('resource', '(see the record)')}", "",
           f"**Knowledge record:** [`{cfg['record']}`](../../{cfg['record']})", "",
           f"**Licence:** {', '.join(cfg.get('licenses', [])) or '(none recorded)'} — see `LICENSE` "
           f"beside this file.", ""]

    if not arts and cfg.get("tier") == "not-shipped":
        # nothing is pinned because nothing is fetched by the build: the loader downloads on the
        # machine of whoever accepts the licence, and the project never mirrors or ships it
        out += ["## Source artifacts", "",
                "**None.** This dataset's licence forbids publishing the data as a stand-alone",
                "dataset, so the build never downloads it, `manifest.yaml` lists nothing for it, and",
                "no release asset exists. `scripts/bikeshare.py` fetches one month from the",
                "operator's own bucket, on the machine of whoever accepts the licence, and records",
                "the key, its sha256 and its `LastModified` in the generated SQL and the table",
                "comment. See the open question on redistribution in the knowledge bundle.", ""]
    elif not arts and cfg.get("tier") == "generated":
        # nothing is downloaded at all: the data comes out of a generator compiled from a pinned
        # commit. Saying "every byte, pinned" above an empty table would be a false claim.
        out += ["## Source artifacts", "",
                "**None downloaded.** This dataset is generated on the machine that builds it, so",
                "there is no upstream file to pin and nothing of it is redistributed. What is pinned",
                "is the *generator*: `docker/loader.Dockerfile` fixes the source commit it is built",
                "from, and the loader records the commit it actually ran. The knowledge record for",
                "this dataset states the cardinalities the specification requires, which is what the",
                "tests assert instead of a content digest.", ""]
    else:
        out += ["## Source artifacts", "",
                "Every byte this database is built from, pinned. `scripts/fetch.py` refuses to proceed if",
                "a download does not match.", "",
                "| artifact | bytes | sha256 |", "|---|---:|---|"]
        for art in arts:
            size = art.get("size_bytes") or 0
            out.append(f"| `{art['id']}` | {size:,} | `{art.get('sha256') or '(unpinned)'}` |")
        if not arts:
            out.append("| (none listed in manifest.yaml) | | |")
        out.append("")

    if "Source artifact" in sections:
        out += ["## What upstream publishes", "", sections["Source artifact"], ""]
    if "License and attribution" in sections:
        out += ["## Licence and attribution, as recorded", "",
                sections["License and attribution"], ""]

    if cfg.get("build_license"):
        # A dataset whose *build* needs proprietary software the image never contains. The point of
        # this section is that a reader can see what they would be agreeing to before they run it.
        bmeta, bsections = licences[cfg["build_license"]]
        out += ["## Build-time software and its licence", "",
                f"Re-deriving this database from upstream runs software under a licence you must",
                f"accept: **{bmeta['title']}** ({bmeta.get('resource', '')}).", "",
                bsections.get("Where the text lives", ""), "",
                bsections.get("Key terms (verbatim)", ""), "",
                "Nothing licensed under those terms is redistributed here: the container is deleted",
                "when the export finishes, and only the exported data — which carries the licence",
                "named above — is kept. **Using the published image does not involve it**, and",
                "neither does building any other dataset.", "",
                section_starting(bsections, "Accepted"), ""]

    out += ["## Transformation", ""]
    converter = os.path.join(ROOT, "datasets", name, "convert.py")
    if os.path.exists(converter):
        first = open(converter, encoding="utf-8").read().split('"""')
        summary = first[1].strip().split("\n\n")[0].replace("\n", " ") if len(first) > 1 else ""
        out += [f"Converted by [`datasets/{name}/convert.py`](convert.py). {summary}", ""]
    else:
        out += [f"Staged by [`scripts/stage.py`](../../scripts/stage.py); no dataset-specific "
                f"converter.", ""]
    name_map = os.path.join(ROOT, "docker", "context", name, "name_map.yaml")
    if os.path.exists(name_map):
        renames = sum(1 for line in open(name_map, encoding="utf-8") if ":" in line
                      and not line.startswith("#"))
        out += [f"{renames} identifiers were renamed; the mapping is written to "
                f"`name_map.yaml` beside the staged SQL at build time.", ""]
    if "Programmable objects" in sections:
        out += ["What was and was not ported:", "", sections["Programmable objects"], ""]

    if measurements:
        counts_path = os.path.join(ROOT, "datasets", name, "tests", "expected_counts.yaml")
        if os.path.exists(counts_path):
            counts = yaml.safe_load(open(counts_path, encoding="utf-8"))
            total = sum(v for v in counts.values() if isinstance(v, int))
            out += ["## Measured", "",
                    f"{len(counts)} tables, {total:,} rows. Per-table counts, digests, index sets,",
                    "query plans and canonical query results are pinned under `tests/` and are",
                    "checked on every build.", ""]
    return "\n".join(out).rstrip() + "\n"


def build_licenses_md(all_datasets, licences):
    used = {}
    for name, cfg in all_datasets:
        for licence_id in cfg.get("licenses", []):
            used.setdefault(licence_id, []).append(name)
    out = [GENERATED, "# Licences", "",
           "This project ships no data of its own. **There is no single licence for the data**: each",
           "database keeps the licence of the project it came from, listed below, and each",
           "`datasets/<name>/LICENSE` carries the terms in full. The project's own code is MIT.", "",
           "| database | licence |", "|---|---|"]
    for name, cfg in all_datasets:
        ids = ", ".join(f"[{i}](knowledge/licenses/{i}.md)" for i in cfg.get("licenses", []))
        out.append(f"| `{name}` | {ids or '—'} |")
    out += ["", "## Licences in use", ""]
    for licence_id in sorted(used):
        meta, _ = licences[licence_id]
        out.append(f"* **{meta['title']}** — {', '.join(f'`{n}`' for n in sorted(used[licence_id]))}")
    return "\n".join(out).rstrip() + "\n"


def build_notice(all_datasets, licences):
    out = [GENERATED, "# NOTICE", "",
           "Attribution required by the licences of the data this image redistributes. The full terms",
           "are in each `datasets/<name>/LICENSE` and in `LICENSES.md`.", ""]
    seen = set()
    for name, cfg in all_datasets:
        for licence_id in cfg.get("licenses", []):
            if licence_id in seen:
                continue
            seen.add(licence_id)
            meta, sections = licences[licence_id]
            if "Attribution" not in sections:
                continue
            out += [f"## {meta['title']}", "", sections["Attribution"], ""]

    # Software used to *produce* a dataset, which the image never contains. It appears here because
    # NOTICE is where someone looks to find out what licences this project involves, and "you are
    # not agreeing to this by using the image, but you would be by rebuilding that dataset" is
    # exactly the kind of thing that should not be buried.
    build = {}
    for name, cfg in all_datasets:
        if cfg.get("build_license"):
            build.setdefault(cfg["build_license"], []).append(name)
    for licence_id, names in sorted(build.items()):
        meta, sections = licences[licence_id]
        out += [f"## Build-time only — {meta['title']}", "",
                f"Rebuilding {' and '.join(f'`{n}`' for n in sorted(names))} from upstream runs "
                f"software under these terms:", "", meta.get("resource", ""), "",
                sections.get("Key terms (verbatim)", ""), "",
                "**You do not accept them by using this image**, and no code covered by them is in "
                "it. You accept them if you run `make wwi-export` yourself, which refuses to start "
                "until you say so explicitly. See "
                + ", ".join(f"`datasets/{n}/PROVENANCE.md`" for n in sorted(names)) + ".", ""]
    return "\n".join(out).rstrip() + "\n"


MEASURED = "\n## Measured\n"


def write(path, content, check, changed, ignore_measured=False):
    existing = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if ignore_measured and existing is not None and MEASURED in existing:
        # CI regenerates without measurements and can only compare the knowledge-derived part:
        # build/ is git-ignored and CI builds a subset, so the Measured section is not reproducible
        # there (PLAN.md 8.3). Everything above it must still match exactly.
        existing = existing[:existing.index(MEASURED)].rstrip() + "\n"
        content = content.rstrip() + "\n"
    if existing == content:
        return
    changed.append(os.path.relpath(path, ROOT))
    if not check:
        open(path, "w", encoding="utf-8").write(content)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--no-measurements", action="store_true",
                    help="omit the sections that need a build (what CI uses)")
    ap.add_argument("--check", action="store_true", help="write nothing; exit 1 if anything differs")
    a = ap.parse_args()

    licences = {}
    for path in sorted(os.listdir(os.path.join(ROOT, "knowledge", "licenses"))):
        if path.endswith(".md") and path != "index.md":
            licences[path[:-3]] = read_record(os.path.join(ROOT, "knowledge", "licenses", path))

    arts = artifacts_by_dataset()
    all_datasets = list(datasets())
    changed = []
    for name, cfg in all_datasets:
        directory = os.path.join(ROOT, "datasets", name)
        missing = [i for i in cfg.get("licenses", []) if i not in licences]
        if missing:
            sys.exit(f"{name}: dataset.yaml names licence(s) with no record: {missing}")
        record = read_record(os.path.join(ROOT, cfg["record"]))
        write(os.path.join(directory, "LICENSE"),
              build_license_file(name, cfg, licences), a.check, changed)
        write(os.path.join(directory, "PROVENANCE.md"),
              build_provenance(name, cfg, arts.get(name, []), record, not a.no_measurements,
                               licences),
              a.check, changed, ignore_measured=a.no_measurements)
    write(os.path.join(ROOT, "LICENSES.md"),
          build_licenses_md(all_datasets, licences), a.check, changed)
    write(os.path.join(ROOT, "NOTICE.md"), build_notice(all_datasets, licences), a.check, changed)

    if a.check and changed:
        print("these generated files are stale; run `make provenance`:")
        for path in changed:
            print(f"  {path}")
        sys.exit(1)
    print(f"  . {len(all_datasets)} datasets, {len(licences)} licence records; "
          f"{len(changed) or 'no'} file(s) {'would change' if a.check else 'written'}")


if __name__ == "__main__":
    main()
