#!/usr/bin/env python3
"""Generate docker/init/10-registry.sql, the only writer of the megasamples.datasets table.

  python3 scripts/registry.py sakila chinook northwind pubs

Rows are built from the four places that already hold the facts -- datasets/<name>/dataset.yaml,
manifest.yaml plus downloads/<id>.meta.json for the source artifacts, build/dumps/<name>.json for
the built artifact, and tests/expected_counts.yaml for the row counts -- so provenance is queryable
from SQL without anyone maintaining a second copy by hand.
"""
import argparse, json, os, sys
import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def esc(value):
    return "'" + str(value).replace("\\", "\\\\").replace("'", "''") + "'"


def row(dataset, build_id):
    d = os.path.join(ROOT, "datasets", dataset)
    cfg = yaml.safe_load(open(os.path.join(d, "dataset.yaml"), encoding="utf-8"))
    counts_path = os.path.join(d, "tests", "expected_counts.yaml")
    counts = yaml.safe_load(open(counts_path, encoding="utf-8")) if os.path.exists(counts_path) else {}

    artifacts = []
    for art_id in cfg.get("artifacts") or []:
        meta_path = os.path.join(ROOT, "downloads", art_id + ".meta.json")
        entry = {"id": art_id}
        if os.path.exists(meta_path):
            meta = json.load(open(meta_path, encoding="utf-8"))
            entry.update({"sha256": meta.get("sha256"), "bytes": meta.get("size_bytes"),
                          "source": meta.get("source")})
        artifacts.append(entry)
    dump_path = os.path.join(ROOT, "build", "dumps", f"{dataset}.json")
    if os.path.exists(dump_path):
        dump = json.load(open(dump_path, encoding="utf-8"))
        artifacts.append({"id": f"dump/{dataset}", "sha256": dump["sha256"], "bytes": dump["bytes"]})

    return (f"({esc(cfg['database'])}, {esc(cfg.get('tier','core'))}, {esc(cfg['record'])}, "
            f"{esc(cfg.get('upstream_version','') or '')}, "
            f"{esc(json.dumps(cfg.get('licenses') or []))}, {esc(json.dumps(artifacts))}, "
            f"{esc(json.dumps(counts))}, {esc(build_id)})")


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("datasets", nargs="+")
    ap.add_argument("--build-id", default=os.environ.get("MEGASAMPLES_BUILD_ID", "dev"))
    ap.add_argument("--out", default=os.path.join(ROOT, "docker", "init", "10-registry.sql"))
    a = ap.parse_args()
    rows = [row(name, a.build_id) for name in sorted(a.datasets)]
    sql = ("-- Generated by scripts/registry.py. Do not edit; it is rewritten on every image build\n"
           "-- and is git-ignored. The table itself is created by 00-users.sql.\n"
           "DELETE FROM megasamples.datasets;\n"
           "INSERT INTO megasamples.datasets\n"
           "  (name, tier, record, upstream_version, licenses, artifacts, row_counts, build_id)\n"
           "VALUES\n  " + ",\n  ".join(rows) + ";\n")
    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    open(a.out, "w", encoding="utf-8").write(sql)
    print(f"  . registry: {len(rows)} dataset(s) -> {os.path.relpath(a.out, ROOT)}")


if __name__ == "__main__":
    main()
