"""Emit DDL for a Table in one of the target dialects. One walk, two dialects, one policy.

    schema(table, dialect)       CREATE TABLE with primary key, NOT NULL, defaults, generated columns
                                 and the enum CHECKs
    indexes(table, dialect)      CREATE [UNIQUE] INDEX for every btree index that is not the primary key
    constraints(table, dialect)  ALTER TABLE ... ADD FOREIGN KEY / ADD CHECK

Index names are prefixed with the table name because PostgreSQL and SQLite scope them to the
schema, where MySQL scopes them to the table; the verification adapters strip the prefix again so
`tests/indexes.yaml` is compared by MySQL's names. What a dialect cannot carry is returned in the
`dropped` list with a reason, never silently skipped: FULLTEXT and SPATIAL indexes, ON UPDATE
CURRENT_TIMESTAMP, and CHECKs whose functions the dialect lacks.
"""
import hashlib, re

from megasamples.port import typemap

NAME_LIMIT = 63     # PostgreSQL truncates longer identifiers silently; SQLite has no limit but shares the rule


def short_name(name):
    """`name` unchanged when it fits PostgreSQL's 63-byte limit, else a stable shortening with a
    hash suffix, so no identifier is ever truncated silently by the server."""
    if len(name.encode("utf-8")) <= NAME_LIMIT:
        return name
    digest = hashlib.sha1(name.encode("utf-8")).hexdigest()[:8]
    head = name.encode("utf-8")[:NAME_LIMIT - 9].decode("utf-8", "ignore")
    return f"{head}_{digest}"


def physical_index_name(table, index):
    """The index name the target carries: `<table>_<index>`, scoped to the schema as PostgreSQL and
    SQLite require, shortened when it exceeds 63 bytes. The verification adapters compute the same
    name to map observed indexes back to MySQL's names."""
    return short_name(f"{table}_{index}")

DROP_FULLTEXT = "FULLTEXT index: not ported"
DROP_SPATIAL = "SPATIAL index: not ported"


class Dialect:
    name = ""
    inline_constraints = False     # True where ALTER TABLE cannot add a constraint later (SQLite)

    def quote(self, ident):
        return '"' + ident.replace('"', '""') + '"'

    def literal(self, text):
        return "'" + text.replace("'", "''") + "'"

    def type(self, col):
        raise NotImplementedError

    def check_functions(self):
        """Functions a CHECK clause may use in this dialect; others cause the check to be dropped."""
        return {"upper", "lower", "length", "abs", "regexp_like"}

    def generated(self, col, expr):
        return f"GENERATED ALWAYS AS ({expr}) STORED"

    def identity(self, col):
        raise NotImplementedError

    def create_index(self, table, index):
        cols = ", ".join(self.quote(c) for c, _ in index.columns)
        uniq = "UNIQUE " if index.unique else ""
        return f"CREATE {uniq}INDEX {self.quote(physical_index_name(table.name, index.name))} ON {self.quote(table.name)} ({cols});"


class Postgres(Dialect):
    name = "postgres"

    def type(self, col):
        return typemap.postgres(col)

    def identity(self, col):
        return "GENERATED BY DEFAULT AS IDENTITY"

    def bytes_literal(self, raw):
        return "'\\x" + raw.hex() + "'::bytea"


class SQLite(Dialect):
    name = "sqlite"
    inline_constraints = True

    def type(self, col):
        return typemap.sqlite(col)

    def check_functions(self):
        return {"upper", "lower", "length", "abs"}      # no regexp_like: dropped, with a reason

    def identity(self, col):
        return ""                                        # INTEGER PRIMARY KEY is the rowid alias

    def bytes_literal(self, raw):
        return "X'" + raw.hex() + "'"


DIALECTS = {"postgres": Postgres(), "sqlite": SQLite()}


def translate_expr(expr, dialect):
    """MySQL's rendering of an expression -> the dialect: backticks to double quotes, charset-prefixed
    literals to plain literals, ifnull to coalesce."""
    out = re.sub(r"`([^`]*)`", lambda m: dialect.quote(m.group(1)), expr)
    # MySQL renders a check clause's literals as _utf8mb4\'X\' -- the quotes backslash-escaped --
    # so the escaped form is matched first, then the plain _utf8mb4'X' form
    out = re.sub(r"_utf8mb4\\'((?:[^\\']|\\[^'])*)\\'", lambda m: dialect.literal(m.group(1)), out)
    out = re.sub(r"_utf8mb4'((?:[^'\\]|\\.)*)'", lambda m: dialect.literal(m.group(1).replace("\\'", "'")), out)
    out = re.sub(r"\bifnull\(", "coalesce(", out)
    return out


def functions_in(expr):
    return {m.lower() for m in re.findall(r"\b([a-z_]+)\(", expr)}


def default_clause(col, dialect):
    """The DEFAULT clause, or "" when there is none. Returns (clause, dropped_reason)."""
    if col.default is None or col.generated:
        return "", None
    if col.default_is_expression:
        expr = col.default.strip()
        if expr.lower() in ("now()", "current_timestamp", "current_timestamp()"):
            return "DEFAULT CURRENT_TIMESTAMP", None
        return "", f"default expression {expr!r} not ported"
    d = col.default
    if typemap.is_binary(col):
        return f"DEFAULT {dialect.bytes_literal(d.encode('utf-8'))}", None
    if typemap.is_textual(col) or col.data_type in ("date", "datetime", "timestamp", "time"):
        if d.startswith("0x") and col.charset is None:
            d = bytes.fromhex(d[2:]).decode("utf-8")   # a text default on a binary-charset table
        return f"DEFAULT {dialect.literal(d)}", None
    return f"DEFAULT {d}", None


def column_def(table, col, dialect, dropped):
    parts = [dialect.quote(col.name), dialect.type(col)]
    pk = table.primary_key
    single_int_pk = bool(pk) and pk.columns == [(col.name, None)] and col.data_type in typemap.INT_PG
    if col.generated:
        parts.append(dialect.generated(col, translate_expr(col.generation, dialect)))
    elif col.auto_increment:
        if dialect.name == "sqlite" and single_int_pk:
            parts = [dialect.quote(col.name), "INTEGER PRIMARY KEY"]   # the rowid alias auto-increments
        else:
            ident = dialect.identity(col)
            if ident:
                parts.append(ident)
    if not (dialect.name == "sqlite" and col.auto_increment and single_int_pk):
        if not col.nullable:
            parts.append("NOT NULL")
        clause, reason = default_clause(col, dialect)
        if clause:
            parts.append(clause)
        if reason:
            dropped.append(f"{table.name}.{col.name}: {reason}")
    if col.on_update_now:
        dropped.append(f"{table.name}.{col.name}: ON UPDATE CURRENT_TIMESTAMP not ported")
    if col.data_type == "enum":
        members = ", ".join(dialect.literal(v) for v in col.enum_values)
        parts.append(f"CHECK ({dialect.quote(col.name)} IN ({members}))")
    return " ".join(parts)


def schema(table, dialect):
    """(CREATE TABLE statement, dropped). The primary key is declared here; nothing else is."""
    dropped = []
    lines = [column_def(table, c, dialect, dropped) for c in table.columns]
    pk = table.primary_key
    sqlite_rowid_pk = (dialect.name == "sqlite" and pk and len(pk.columns) == 1
                       and table.column(pk.columns[0][0]).auto_increment
                       and table.column(pk.columns[0][0]).data_type in typemap.INT_PG)
    if pk and not sqlite_rowid_pk:
        cols = ", ".join(dialect.quote(c) for c, _ in pk.columns)
        lines.append(f"PRIMARY KEY ({cols})")
    if dialect.inline_constraints:
        clauses, d = constraint_clauses(table, dialect)
        lines += clauses
        dropped += d
    body = ",\n  ".join(lines)
    return f"CREATE TABLE {dialect.quote(table.name)} (\n  {body}\n);", dropped


def indexes(table, dialect):
    """(statements, dropped) for every secondary index the dialect can carry."""
    out, dropped = [], []
    for index in table.indexes:
        if index.primary:
            continue
        if index.type == "FULLTEXT":
            dropped.append(f"{table.name}.{index.name}: {DROP_FULLTEXT}")
            continue
        if index.type == "SPATIAL":
            dropped.append(f"{table.name}.{index.name}: {DROP_SPATIAL}")
            continue
        out.append(dialect.create_index(table, index))
    return out, dropped


ACTIONS = {"NO ACTION": "NO ACTION", "CASCADE": "CASCADE", "SET NULL": "SET NULL",
           "RESTRICT": "RESTRICT", "SET DEFAULT": "SET DEFAULT"}


def constraint_clauses(table, dialect):
    """(clauses, dropped): every foreign key and CHECK as a table-constraint clause.

    A foreign key into another database is dropped on both targets: PostgreSQL cannot reference
    another database and SQLite files are separate; the catalogue records it.
    """
    out, dropped = [], []
    for fk in table.foreign_keys:
        if fk.ref_schema != table.schema:
            dropped.append(f"{table.name}.{fk.name}: foreign key into {fk.ref_schema}.{fk.ref_table} (another database) not ported")
            continue
        cols = ", ".join(dialect.quote(c) for c in fk.columns)
        rcols = ", ".join(dialect.quote(c) for c in fk.ref_columns)
        out.append(f"CONSTRAINT {dialect.quote(short_name(fk.name))} FOREIGN KEY ({cols}) "
                   f"REFERENCES {dialect.quote(fk.ref_table)} ({rcols}) "
                   f"ON UPDATE {ACTIONS[fk.on_update]} ON DELETE {ACTIONS[fk.on_delete]}")
    for check in table.checks:
        missing = functions_in(check.clause) - dialect.check_functions()
        if missing:
            dropped.append(f"{table.name}.{check.name}: CHECK uses {', '.join(sorted(missing))}, which {dialect.name} lacks; not ported")
            continue
        out.append(f"CONSTRAINT {dialect.quote(short_name(check.name))} CHECK ({translate_expr(check.clause, dialect)})")
    return out, dropped


def constraints(table, dialect):
    """(statements, dropped): the constraints added after the data is loaded. Empty for a dialect
    that declares them inline, where schema() has already carried them."""
    if dialect.inline_constraints:
        return [], []
    clauses, dropped = constraint_clauses(table, dialect)
    t = dialect.quote(table.name)
    return [f"ALTER TABLE {t} ADD {c};" for c in clauses], dropped


def render(database, dialect_name):
    """Every statement for a database, grouped: {"schema": [...], "indexes": [...], "constraints": [...], "dropped": [...]}."""
    from megasamples.port.model import load_order
    dialect = DIALECTS[dialect_name]
    out = {"schema": [], "indexes": [], "constraints": [], "dropped": []}
    for table in load_order(database):
        s, d = schema(table, dialect)
        out["schema"].append(s)
        out["dropped"] += d
        i, d = indexes(table, dialect)
        out["indexes"] += i
        out["dropped"] += d
        c, d = constraints(table, dialect)
        out["constraints"] += c
        out["dropped"] += d
    for v in database.views:
        out["dropped"].append(f"view {v}: not ported")
    for r in database.routines:
        out["dropped"].append(f"{r}: not ported")
    for tr in database.triggers:
        out["dropped"].append(f"trigger {tr}: not ported")
    return out
