"""Write what a port decided beside the dataset, so the decisions are reviewable in git.

    datasets/<name>/ports/postgres.sql   the DDL the port generated (tables, indexes, constraints)
    datasets/<name>/ports/sqlite.sql
    datasets/<name>/ports/not_ported.yaml  per engine, what was not carried and why
    datasets/<name>/ports/result_sets.yaml the result columns PostgreSQL inferred for each procedure
                                           that returns rows (measured once with psql's \\gdesc)
    datasets/<name>/ports/notes.yaml       what the PostgreSQL routine port changed inside a body

These are generated files: a port rewrites them, and a diff shows exactly which type or index
decision changed. Data never goes here.
"""
import os

import yaml

from megasamples.paths import DATASETS


def write(dataset, engine, rendered):
    d = os.path.join(DATASETS, dataset, "ports")
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, f"{engine}.sql"), "w", encoding="utf-8") as fh:
        fh.write(f"-- {engine} DDL for `{dataset}`, generated by megasamples from the MySQL corpus. Do not edit:\n"
                 f"-- the next port rewrites it. Data is loaded from the MySQL Shell dump, not from here.\n\n")
        fh.write("\n\n".join(rendered["schema"]) + "\n")
        if rendered["indexes"]:
            fh.write("\n" + "\n".join(rendered["indexes"]) + "\n")
        if rendered["constraints"]:
            fh.write("\n" + "\n".join(rendered["constraints"]) + "\n")
        if rendered.get("routines"):
            fh.write("\n" + "\n\n".join(rendered["routines"]) + "\n")
        if rendered.get("views"):
            fh.write("\n" + "\n\n".join(rendered["views"]) + "\n")
        if rendered.get("triggers"):
            fh.write("\n" + "\n\n".join(rendered["triggers"]) + "\n")
    if engine == "postgres":
        write_result_sets(dataset, rendered.get("result_columns") or {})
        with open(os.path.join(d, "notes.yaml"), "w", encoding="utf-8") as fh:
            fh.write(notes_text(rendered.get("notes") or {}))
    path = os.path.join(d, "not_ported.yaml")
    current = {}
    if os.path.exists(path):
        with open(path, encoding="utf-8") as fh:
            current = yaml.safe_load(fh) or {}
    current[engine] = list(rendered["dropped"])
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(not_ported_text(current))


def not_ported_text(per_engine):
    return ("# What each engine's port does not carry, one line per object, with the reason.\n"
            "# Generated by the port; the catalogue and the landing page read it.\n"
            + yaml.safe_dump(per_engine, sort_keys=True, default_flow_style=False, allow_unicode=True, width=120))


def result_sets_path(dataset):
    return os.path.join(DATASETS, dataset, "ports", "result_sets.yaml")


def read_result_sets(dataset):
    """{procedure: [(column, type)]} as recorded, or {}."""
    path = result_sets_path(dataset)
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as fh:
        doc = yaml.safe_load(fh) or {}
    return {name: [tuple(c) for c in cols] for name, cols in doc.items()}


def write_result_sets(dataset, result_columns):
    path = result_sets_path(dataset)
    if not result_columns:
        if os.path.exists(path):
            os.remove(path)
        return
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(result_sets_text(result_columns))


def result_sets_text(result_columns):
    doc = {name: [list(c) for c in cols] for name, cols in result_columns.items()}
    return ("# The result columns PostgreSQL infers for each procedure that returns rows, measured with\n"
            "# psql's \\gdesc on the ported schema; the procedure becomes a function RETURNS TABLE(...).\n"
            + yaml.safe_dump(doc, sort_keys=True, default_flow_style=None, allow_unicode=True, width=120))


def notes_text(notes):
    return ("# What the PostgreSQL port changed inside a routine body, by routine: constructs with no\n"
            "# PL/pgSQL counterpart, replaced by rule (megasamples/port/routines.py).\n"
            + yaml.safe_dump(notes, sort_keys=True, default_flow_style=False, allow_unicode=True, width=120))
