"""Write what a port decided beside the dataset, so the decisions are reviewable in git.

    datasets/<name>/ports/postgres.sql   the DDL the port generated (tables, indexes, constraints)
    datasets/<name>/ports/sqlite.sql
    datasets/<name>/ports/not_ported.yaml  per engine, what was not carried and why

These are generated files: a port rewrites them, and a diff shows exactly which type or index
decision changed. Data never goes here.
"""
import os

import yaml

from megasamples.paths import DATASETS


def write(dataset, engine, rendered):
    d = os.path.join(DATASETS, dataset, "ports")
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, f"{engine}.sql"), "w", encoding="utf-8") as fh:
        fh.write(f"-- {engine} DDL for `{dataset}`, generated by megasamples from the MySQL corpus. Do not edit:\n"
                 f"-- the next port rewrites it. Data is loaded from the MySQL Shell dump, not from here.\n\n")
        fh.write("\n\n".join(rendered["schema"]) + "\n")
        if rendered["indexes"]:
            fh.write("\n" + "\n".join(rendered["indexes"]) + "\n")
        if rendered["constraints"]:
            fh.write("\n" + "\n".join(rendered["constraints"]) + "\n")
    path = os.path.join(d, "not_ported.yaml")
    current = {}
    if os.path.exists(path):
        with open(path, encoding="utf-8") as fh:
            current = yaml.safe_load(fh) or {}
    current[engine] = list(rendered["dropped"])
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(not_ported_text(current))


def not_ported_text(per_engine):
    return ("# What each engine's port does not carry, one line per object, with the reason.\n"
            "# Generated by the port; the catalogue and the landing page read it.\n"
            + yaml.safe_dump(per_engine, sort_keys=True, default_flow_style=False, allow_unicode=True, width=120))
